/* Kitaak web demo — a corporate account, fully in the browser. Nothing is saved. */
(function () {
  "use strict";
  const D = window.KITAAK_DEMO, PLANS = window.KITAAK_PLANS || [], IC = window.KITAAK_ICONS || {};
  if (!D) { document.body.innerHTML = "<p style='padding:40px;font-family:sans-serif'>Demo data missing (demo/demo-data.js).</p>"; return; }
  const $ = (s, r) => (r || document).querySelector(s), $$ = (s, r) => Array.from((r || document).querySelectorAll(s));
  const esc = (s) => String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const h = (html) => { const t = document.createElement("template"); t.innerHTML = String(html).trim(); return t.content.firstElementChild; };
  const icon = (n, size, stroke) => '<svg width="' + (size || 22) + '" height="' + (size || 22) + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="' + (stroke || 2) + '" stroke-linecap="round" stroke-linejoin="round"><path d="' + (IC[n] || "") + '"/></svg>';
  const rnd = (a) => a[Math.floor(Math.random() * a.length)];
  const uid = () => "m" + Math.random().toString(36).slice(2, 9);
  const NOW = () => Date.now();
  const initials = (n) => String(n || "?").split(/\s+/).map((w) => w[0]).slice(0, 2).join("").toUpperCase();
  const pad = (n) => String(n).padStart(2, "0");
  const fmtTime = (t) => { const d = new Date(t); return pad(d.getHours()) + ":" + pad(d.getMinutes()); };
  const fmtConv = (t) => { const d = new Date(t), n = new Date(); if (d.toDateString() === n.toDateString()) return fmtTime(t); const diff = (n - d) / 864e5; if (diff < 6) return d.toLocaleDateString(undefined, { weekday: "short" }); return d.toLocaleDateString(undefined, { month: "short", day: "numeric" }); };
  const dayLabel = (t) => { const d = new Date(t), n = new Date(); if (d.toDateString() === n.toDateString()) return "Today"; const y = new Date(n); y.setDate(n.getDate() - 1); if (d.toDateString() === y.toDateString()) return "Yesterday"; return d.toLocaleDateString(undefined, { weekday: "long", month: "long", day: "numeric" }); };

  // ---------------- state (in memory only) ----------------
  const S = {
    me: Object.assign({}, D.me, { status: "online", statusLine: "", pub: { title: true, department: true, phone: false, email: false, city: true, bio: true } }),
    people: D.people.map((p) => Object.assign({}, p)),
    rooms: [], contacts: new Set(D.people.map((p) => p.id)), blocked: new Set(),
    unread: {}, typing: {}, started: 0, theme: "paper",
    settings: { autoAdd: true, tz: "auto", notif: { messages: true, mentions: true, calls: true, music: false }, reactions: ["👍", "❤️", "🔥", "🎧"], disappearing: "off", isa: false, ism: true, duck: 20, awayAfter: "10", sounds: true },
    signs: {}, hours: {}, shelf: new Set(), callState: null, ddRoom: null,
  };
  const person = (id) => (id === "allison" ? S.me : S.people.find((p) => p.id === id));
  const nameOf = (id) => (person(id) || { name: id }).name;
  const mkMsg = (m) => ({ id: uid(), from: m.from, kind: m.kind || "text", text: m.text || "", file: m.file || null, at: NOW() - (m.minutesAgo || 0) * 60000, reactions: {} });
  D.groups.forEach((g) => S.rooms.push({ id: g.id, type: "group", name: g.name.replace(/^#\s*/, ""), topic: g.topic, memberIds: g.memberIds.filter((i) => i !== "allison").concat(["allison"]), adminId: g.adminId, instantSpeech: Object.assign({ active: false, speakers: [], schedule: { enabled: false, days: [5], from: "17:00", to: "18:00" } }, g.instantSpeech || {}), listenExcept: new Set(), messages: g.messages.map(mkMsg).sort((a, b) => a.at - b.at), disappearing: "off" }));
  D.dms.forEach((d) => S.rooms.push({ id: "dm:" + d.personId, type: "dm", personId: d.personId, name: nameOf(d.personId), messages: d.messages.map(mkMsg).sort((a, b) => a.at - b.at), disappearing: "off" }));
  S.rooms.slice().sort(() => Math.random() - 0.5).slice(0, 7).forEach((r, i) => { S.unread[r.id] = 1 + (i % 3); });
  const lastAt = (r) => (r.messages.length ? r.messages[r.messages.length - 1].at : 0);
  const room = (id) => S.rooms.find((r) => r.id === id);
  const tracksById = {}; D.music.albums.forEach((a) => a.tracks.forEach((t) => { tracksById[t.id] = Object.assign({ albumId: a.id, artistId: a.artistId, cover: a.cover }, t); }));
  const artist = (id) => D.music.artists.find((a) => a.id === id) || { name: "Unknown" };
  const album = (id) => D.music.albums.find((a) => a.id === id);
  const genre = (id) => D.music.genres.find((g) => g.id === id);
  const playlist = (id) => D.music.playlists.find((p) => p.id === id);

  // ---------------- UI helpers ----------------
  let toastT = null;
  function toast(msg, ms) { const old = $(".toast"); if (old) old.remove(); const t = h('<div class="toast">' + esc(msg) + "</div>"); document.body.appendChild(t); clearTimeout(toastT); toastT = setTimeout(() => t.remove(), ms || 2600); }
  function modal(title, bodyHtml, buttons, opts) {
    closeModal();
    const m = h('<div class="modal-scrim" data-modal="1"><div class="modal" role="dialog"><div class="modal-head"><div class="display" style="font-size:19px">' + esc(title) + '</div><button class="icon-btn" data-close title="Close">' + icon("x", 18) + '</button></div><div class="modal-body">' + bodyHtml + '</div>' + (buttons && buttons.length ? '<div class="modal-foot">' + buttons.map((b, i) => '<button class="btn ' + (b.cls || "") + '" data-btn="' + i + '">' + esc(b.label) + "</button>").join("") + "</div>" : "") + "</div></div>");
    m.addEventListener("click", (e) => { if (e.target === m && !(opts && opts.sticky)) closeModal(); });
    $("[data-close]", m).onclick = closeModal;
    (buttons || []).forEach((b, i) => { $('[data-btn="' + i + '"]', m).onclick = () => { const r = b.onClick ? b.onClick(m) : true; if (r !== false) closeModal(); }; });
    $("#overlays").appendChild(m); return m;
  }
  function closeModal() { $$("[data-modal]").forEach((x) => x.remove()); }
  function popover(x, y, html) { closePop(); const p = h('<div class="pop" data-pop="1">' + html + "</div>"); document.body.appendChild(p); const w = p.offsetWidth, hh = p.offsetHeight; p.style.left = Math.max(8, Math.min(x, innerWidth - w - 8)) + "px"; p.style.top = Math.max(8, Math.min(y, innerHeight - hh - 8)) + "px"; setTimeout(() => document.addEventListener("mousedown", popOut, { once: true }), 0); return p; }
  function popOut(e) { if (e.target.closest("[data-pop]")) { document.addEventListener("mousedown", popOut, { once: true }); return; } closePop(); }
  function closePop() { $$("[data-pop]").forEach((x) => x.remove()); }
  let tipEl = null;
  function tip(el, text) { el.addEventListener("mouseenter", () => { tipEl = h('<div class="tip">' + esc(text) + "</div>"); document.body.appendChild(tipEl); const r = el.getBoundingClientRect(); tipEl.style.left = Math.min(r.left, innerWidth - tipEl.offsetWidth - 10) + "px"; tipEl.style.top = (r.bottom + 8 + tipEl.offsetHeight > innerHeight ? r.top - tipEl.offsetHeight - 8 : r.bottom + 8) + "px"; }); el.addEventListener("mouseleave", () => { if (tipEl) tipEl.remove(); tipEl = null; }); el.addEventListener("click", (e) => { e.stopPropagation(); modal("About this", "<p>" + esc(text) + "</p>", [{ label: "Got it", cls: "primary" }]); }); }
  const infoI = (text) => { const i = h('<span class="info-i" title="">i</span>'); tip(i, text); return i; };
  const avatar = (p, size, presence) => { const s = size || 40; const st = p && p.status; return '<span class="avatar" style="width:' + s + "px;height:" + s + "px;font-size:" + Math.round(s * 0.36) + 'px">' + esc(p && p.initials ? p.initials : initials(p && p.name)) + (presence ? '<span class="presence-dot ' + esc(st || "offline") + '"></span>' : "") + "</span>"; };
  const sw = (on, attr) => '<button class="switch ' + (on ? "on" : "") + '" ' + (attr || "") + ' role="switch" aria-checked="' + (on ? "true" : "false") + '"></button>';
  function wireSwitch(el, cb) { el.onclick = () => { el.classList.toggle("on"); el.setAttribute("aria-checked", el.classList.contains("on") ? "true" : "false"); cb(el.classList.contains("on")); }; }

  // ---------------- audio: ambient loop (placeholder music) + ducking ----------------
  const BG_TRACK = { file: "demo/background-music.mp3", title: "Summer Drive", artist: "Bare Frequencies" };
  const Player = {
    ctx: null, audio: null, running: false, volume: 0.7, ducked: false, current: null, fadeT: null,
    ensure() { if (!this.ctx) { const AC = window.AudioContext || window.webkitAudioContext; if (AC) this.ctx = new AC(); } if (this.ctx && this.ctx.state === "suspended") this.ctx.resume(); if (!this.audio) { this.audio = new Audio(BG_TRACK.file); this.audio.loop = true; this.audio.preload = "auto"; this.audio.volume = 0; } return true; },
    targetVol() { return Math.max(0, Math.min(1, this.volume * (this.ducked ? S.settings.duck / 100 : 1))); },
    fadeTo(v, ms) { clearInterval(this.fadeT); const a = this.audio; if (!a) return; const from = a.volume, steps = Math.max(1, Math.round((ms || 400) / 40)); let i = 0; this.fadeT = setInterval(() => { i++; a.volume = from + (v - from) * (i / steps); if (i >= steps) { a.volume = v; clearInterval(this.fadeT); } }, 40); },
    start(label) {
      this.ensure(); this.current = label || (BG_TRACK.title + " — " + BG_TRACK.artist);
      if (this.running) { renderPlayer(); return; }
      this.running = true; this.audio.play().then(() => this.fadeTo(this.targetVol(), 900)).catch(() => { this.running = false; renderPlayer(); toast("Your browser blocked audio — click anywhere, then press play."); }); renderPlayer();
    },
    stop() { if (!this.running) return; this.running = false; this.fadeTo(0, 400); setTimeout(() => { if (!this.running && this.audio) this.audio.pause(); }, 450); renderPlayer(); },
    setVolume(v) { this.volume = v; if (this.running) this.fadeTo(this.targetVol(), 150); renderPlayer(); },
    duck(on) { this.ducked = on; if (this.running) this.fadeTo(this.targetVol(), on ? 350 : 1200); renderPlayer(); },
  };
  function renderPlayer() {
    const el = $("#player"); el.classList.toggle("ducked", Player.ducked);
    el.innerHTML = '<div class="np">' + (Player.running ? '<span class="disc"><span class="eq"><i></i><i></i><i></i></span></span><div><div class="t">' + esc(Player.current) + '</div><div class="a">demo background track · loops while you explore <span class="duck-pill">ducked to ' + S.settings.duck + "% for the conversation</span></div></div>" : '<span class="disc">' + icon("disc", 22) + '</span><div><div class="t">Nothing playing</div><div class="a">Press play for the demo background track · the library itself carries no music files</div></div>') + '</div><div class="ctl"><button class="icon-btn" title="Previous">' + icon("prev", 18) + '</button><button class="pp" id="ppBtn" title="' + (Player.running ? "Pause" : "Play the demo background track") + '">' + icon(Player.running ? "pause" : "play", 20) + '</button><button class="icon-btn" title="Next">' + icon("next", 18) + '</button></div><div class="vol">' + icon("volume", 16) + '<input type="range" min="0" max="100" value="' + Math.round(Player.volume * 100) + '" id="volRange"><span>' + Math.round(Player.volume * 100) + "%</span></div>";
    $("#ppBtn", el).onclick = () => (Player.running ? Player.stop() : Player.start());
    $("#volRange", el).oninput = (e) => Player.setVolume(Number(e.target.value) / 100);
    $$(".icon-btn", el).forEach((b) => (b.onclick = () => toast("Demo: there is no queue — the library carries no music files.")));
  }
  function noMusicPopup(title) {
    modal("This is a demo", '<p style="margin-top:0"><b>This demo does not contain any music.</b></p><p class="muted">In the full application <b>' + esc(title) + "</b> would play here — and it would duck automatically the moment someone talks to you, then come back up when the conversation ends.</p><p class=\"muted\" style=\"font-size:13px\">Keep the demo background track playing instead — you will hear it duck the moment someone talks to you.</p>",
      [{ label: "Play the demo background track", cls: "primary", onClick: () => Player.start() }, { label: "Close" }]);
  }

  // ---------------- the Digital Demonstrator call ----------------
  const Call = {
    audio: null, ringT: null, ringOsc: [], startAt: 0, tick: null,
    ring() { if (!Player.ensure()) return; const play = () => { const t = Player.ctx.currentTime; [[440, 0], [554, 0.35]].forEach(([f, d]) => { const o = Player.ctx.createOscillator(), g = Player.ctx.createGain(); o.frequency.value = f; g.gain.value = 0; g.gain.setTargetAtTime(0.12, t + d, 0.02); g.gain.setTargetAtTime(0, t + d + 0.3, 0.05); o.connect(g); g.connect(Player.ctx.destination); o.start(t + d); o.stop(t + d + 0.7); }); }; play(); this.ringT = setInterval(play, 2200); },
    stopRing() { clearInterval(this.ringT); this.ringT = null; },
    incoming() {
      if (S.callState) return; S.callState = "ringing"; this.ring();
      const ov = h('<div class="call-overlay" id="callOv"><div class="call-card"><div class="big">DD</div><div class="nm">Digital Demonstrator</div><div class="st">Incoming voice call · Kitaak</div><div class="muted" style="font-size:13px;margin-bottom:16px">Answer to hear the message. Your music ducks while the call is live and comes back afterwards.</div><div class="btns"><button class="btn danger" id="declineBtn">' + icon("phoneoff", 18) + ' Decline</button><button class="btn green" id="answerBtn">' + icon("phone", 18) + " Answer</button></div></div></div>");
      $("#overlays").appendChild(ov);
      $("#declineBtn", ov).onclick = () => this.decline(); $("#answerBtn", ov).onclick = () => this.answer();
      setTimeout(() => { if (S.callState === "ringing") this.decline(true); }, 45000);
    },
    answer() {
      this.stopRing(); S.callState = "live"; Player.duck(true);
      const ov = $("#callOv"); ov.innerHTML = '<div class="call-card"><div class="big" style="animation:none">DD</div><div class="nm">Digital Demonstrator</div><div class="st" id="callTimer">00:00 · connected</div><div class="wave">' + "<i></i>".repeat(24) + '</div><div class="muted" style="font-size:13px;margin-bottom:14px">Music ducked to ' + S.settings.duck + "% · it rises back when the message ends.</div><div class=\"btns\"><button class=\"btn danger\" id=\"hangBtn\">" + icon("phoneoff", 18) + " Hang up</button></div></div>";
      this.startAt = NOW(); this.tick = setInterval(() => { const s = Math.floor((NOW() - this.startAt) / 1000); const t = $("#callTimer"); if (t) t.textContent = pad(Math.floor(s / 60)) + ":" + pad(s % 60) + " · live"; }, 500);
      $("#hangBtn").onclick = () => this.end("hung up");
      const a = new Audio("demo/demo-voice-message.mp3"); this.audio = a; a.volume = 1; a.onended = () => this.end("message finished"); a.onerror = () => { toast("The demo voice message could not be loaded."); this.end("error"); }; a.play().catch(() => { toast("Click anywhere to allow audio, then answer again."); });
    },
    end(why) {
      if (S.callState !== "live") return; S.callState = "done"; clearInterval(this.tick); if (this.audio) { try { this.audio.pause(); } catch (e) {} } Player.duck(false);
      const ov = $("#callOv"); if (ov) ov.remove();
      const dur = Math.round((NOW() - this.startAt) / 1000);
      this.leaveMessage(true, dur); toast("Call ended (" + why + ") — the music is back to your level.");
    },
    decline(timeout) { this.stopRing(); S.callState = "missed"; const ov = $("#callOv"); if (ov) ov.remove(); this.leaveMessage(false, 0); toast(timeout ? "Missed call from Digital Demonstrator" : "Call declined — Digital Demonstrator left you a voice message instead."); },
    leaveMessage(answered, dur) {
      let r = S.ddRoom; if (!r) { r = { id: "dm:demonstrator", type: "dm", personId: "demonstrator", name: "Digital Demonstrator", messages: [], disappearing: "off" }; S.rooms.push(r); S.ddRoom = r; }
      r.messages.push({ id: uid(), from: "demonstrator", kind: "call", text: answered ? "Voice call · " + pad(Math.floor(dur / 60)) + ":" + pad(dur % 60) : "Missed voice call", at: NOW(), reactions: {} });
      r.messages.push({ id: uid(), from: "demonstrator", kind: "voice", text: "Voice message · 0:39", playable: true, at: NOW() + 1, reactions: {} });
      r.messages.push({ id: uid(), from: "demonstrator", kind: "text", text: answered ? "Thanks for taking my call! That was Kitaak's audio priority at work: the music stepped aside while I talked and came back the moment I stopped. Everything else in this demo works too — go ahead and explore." : "Sorry I missed you. Tap the voice message above to hear what I wanted to say — your music will duck while it plays and rise back afterwards.", at: NOW() + 2, reactions: {} });
      if (curRoomId !== r.id) S.unread[r.id] = (S.unread[r.id] || 0) + 2;
      renderNav(); if (page === "chat") renderChat(curRoomId);
    },
    playVoice() { if (S.callState === "live") return; const a = new Audio("demo/demo-voice-message.mp3"); Player.duck(true); toast("Playing the voice message — music ducked to " + S.settings.duck + "%"); a.onended = () => { Player.duck(false); toast("Message finished — music back up."); }; a.play().catch(() => toast("Click anywhere first to allow audio.")); },
  };
  window.__demoAvatarPerson = { demonstrator: { id: "demonstrator", name: "Digital Demonstrator", initials: "DD", status: "online", title: "Your guide to Kitaak", department: "Kitaak", oNumber: "O0", bio: "Calls every visitor once, to show how a conversation takes priority over the music." } };
  const personX = (id) => person(id) || window.__demoAvatarPerson[id] || { id, name: id, initials: "?" };

  // ---------------- navigation ----------------
  let page = "chat", curRoomId = null, musicSub = { kind: "home" };
  const NAV = [["chat", "Studio", "chat"], ["contacts", "Contacts", "contacts"], ["music", "The Music Library", "music"], ["search", "Dig", "search"], ["files", "Media", "file"], ["company", D.company.name, "briefcase"], ["settings", "Settings", "settings"]];
  function renderNav() {
    const n = $("#nav"); const unread = Object.values(S.unread).reduce((a, b) => a + b, 0);
    n.innerHTML = '<div class="brand-block"><img class="brand-mark" src="demo/icon.svg" alt="Kitaak"><div class="brand-name">kitaak</div><div class="brand-divider"></div></div>' + NAV.map(([k, label, ic]) => '<a class="nav-item ' + (page === k ? "active" : "") + '" href="#/' + k + '" title="' + esc(label) + '">' + icon(ic, 22) + (k === "chat" && unread ? '<span class="badge">' + unread + "</span>" : "") + "</a>").join("") + '<div class="nav-spacer"></div><a class="nav-item ' + (page === "profile" ? "active" : "") + '" href="#/profile" title="' + esc(S.me.name) + '">' + avatar(S.me, 36, true) + "</a>";
  }
  function route() {
    closePop(); closeModal();
    const hash = location.hash || "#/chat"; const parts = hash.replace(/^#\//, "").split("?")[0].split("/"); const q = new URLSearchParams(hash.split("?")[1] || "");
    page = parts[0] || "chat";
    if (page === "chat") { curRoomId = parts[1] ? decodeURIComponent(parts[1]) : null; renderChat(curRoomId); }
    else if (page === "contacts") renderContacts(q.get("q") || "");
    else if (page === "music") { musicSub = { kind: parts[1] || "home", id: parts[2] ? decodeURIComponent(parts[2]) : null, q: q.get("q") || "" }; renderMusic(); }
    else if (page === "search") renderSearch(q.get("q") || "");
    else if (page === "files") renderFiles();
    else if (page === "company") renderCompany();
    else if (page === "settings") renderSettings();
    else if (page === "profile") renderProfile();
    else if (page === "membership") renderMembership();
    else { location.hash = "#/chat"; return; }
    renderNav();
  }
  window.addEventListener("hashchange", route);

  // ---------------- CHAT ----------------
  function roomTitle(r) { return r.type === "group" ? "# " + r.name : r.name; }
  function snippet(m) { if (!m) return "No messages yet"; const who = m.from === "allison" ? "You: " : ""; if (m.kind === "voice") return who + "🎤 Voice message"; if (m.kind === "file") return who + "📎 " + (m.file ? m.file.name : m.text); if (m.kind === "call") return "📞 " + m.text; if (m.kind === "system") return m.text; return who + m.text; }
  function renderChat(roomId) {
    const list = S.rooms.slice().sort((a, b) => lastAt(b) - lastAt(a));
    const main = $("#main"); const r = roomId ? room(roomId) : null;
    if (r) delete S.unread[r.id];
    main.innerHTML = '<div class="chat-shell ' + (r ? "in-room" : "") + '"><div class="conv-list"><div class="conv-search"><input class="input" id="convQ" placeholder="Search conversations"></div><div class="conv-scroll thin-scroll" id="convScroll"></div></div><div class="thread" id="thread"></div></div>';
    const scroll = $("#convScroll");
    const paint = (q) => { scroll.innerHTML = list.filter((x) => !q || roomTitle(x).toLowerCase().includes(q)).map((x) => { const p = x.type === "dm" ? personX(x.personId) : null; const last = x.messages[x.messages.length - 1]; return '<button class="conv-item ' + (r && r.id === x.id ? "active" : "") + '" data-room="' + esc(x.id) + '"><div style="position:relative">' + (p ? avatar(p, 48, true) : '<span class="avatar" style="width:48px;height:48px;font-size:18px">#</span>') + '</div><div class="conv-main"><div class="conv-top"><span class="conv-name">' + esc(roomTitle(x)) + '</span><span class="conv-time">' + (last ? fmtConv(last.at) : "") + '</span></div><div class="conv-snippet">' + esc(snippet(last)) + "</div></div>" + (S.unread[x.id] ? '<span class="unread-badge">' + S.unread[x.id] + "</span>" : "") + "</button>"; }).join(""); $$("[data-room]", scroll).forEach((b) => (b.onclick = () => (location.hash = "#/chat/" + encodeURIComponent(b.dataset.room)))); };
    paint(""); $("#convQ").oninput = (e) => paint(e.target.value.trim().toLowerCase());
    const th = $("#thread");
    if (!r) { th.innerHTML = '<div class="empty-state"><div class="inner"><img class="disc" src="demo/icon.svg" alt="" style="width:80px;margin:0 auto 12px"><h1 class="display" style="font-size:26px">Your conversations live here</h1><p class="muted">Pick a chat on the left. You are signed in as ' + esc(S.me.name) + " at " + esc(D.company.name) + " — try sending something; your colleagues answer.</p></div></div>"; return; }
    const p = r.type === "dm" ? personX(r.personId) : null;
    const sub = r.type === "group" ? r.memberIds.length + " members · " + (r.topic || "") + (r.instantSpeech.active ? " · ● LIVE instant speech" : "") : (p.title || "") + (p.department ? " · " + p.department : "") + " · " + (p.status || "offline");
    th.innerHTML = '<div class="thread-head"><button class="icon-btn back" id="backBtn" title="Back">' + icon("back", 18) + '</button>' + (p ? avatar(p, 40, true) : '<span class="avatar" style="width:40px;height:40px">#</span>') + '<div class="grow"><div class="title" title="Group info" style="cursor:pointer" id="threadTitle">' + esc(roomTitle(r)) + (r.instantSpeech && r.instantSpeech.active ? ' <span class="chip" style="background:var(--rust);color:#fff;border-color:transparent;font-size:10px">● LIVE instant speech</span>' : "") + '</div><div class="sub">' + esc(sub) + '</div></div><button class="icon-btn" id="callBtn" title="Voice call">' + icon("phone", 20) + '</button><button class="icon-btn" id="videoBtn" title="Video call">' + icon("video", 20) + '</button><button class="icon-btn" id="infoBtn" title="' + (r.type === "group" ? "Group info" : "Profile & chat settings") + '">' + icon(r.type === "group" ? "people" : "user", 20) + '</button></div><div class="msgs thin-scroll" id="msgs"></div><div class="typing" id="typing"></div><div class="composer"><button class="icon-btn" id="attachBtn" title="Attach a file">' + icon("attach", 20) + '</button><textarea class="input" id="composer" placeholder="Message ' + esc(roomTitle(r)) + '" rows="1"></textarea><button class="icon-btn" id="micBtn" title="Record a voice message">' + icon("mic", 20) + '</button><button class="send-btn" id="sendBtn" title="Send">' + icon("send", 18) + "</button></div>";
    $("#backBtn").onclick = () => (location.hash = "#/chat"); $("#threadTitle").onclick = () => (r.type === "group" ? groupInfo(r) : profilePopup(p));
    $("#infoBtn").onclick = () => (r.type === "group" ? groupInfo(r) : profilePopup(p)); $("#callBtn").onclick = () => simCall(r, "voice"); $("#videoBtn").onclick = () => simCall(r, "video");
    $("#attachBtn").onclick = () => { const f = rnd(D.files); send(r, { kind: "file", text: f.name, file: { name: f.name, kind: f.kind, size: f.size } }); toast("Demo: a sample file was attached instead of a real upload."); };
    $("#micBtn").onclick = () => { send(r, { kind: "voice", text: "Voice message · 0:07" }); toast("Demo: recording is simulated — a voice message was sent."); };
    const ta = $("#composer"); const doSend = () => { const t = ta.value.trim(); if (!t) return; ta.value = ""; send(r, { kind: "text", text: t }); };
    $("#sendBtn").onclick = doSend; ta.onkeydown = (e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); doSend(); } };
    paintMsgs(r); setTimeout(() => ta.focus(), 50);
  }
  function paintMsgs(r) {
    const box = $("#msgs"); if (!box) return; let lastDay = ""; let html = "";
    r.messages.forEach((m, i) => {
      const day = dayLabel(m.at); if (day !== lastDay) { html += '<div class="day-sep">' + esc(day) + "</div>"; lastDay = day; }
      const mine = m.from === "allison"; const p = personX(m.from); const prev = r.messages[i - 1]; const showName = r.type === "group" && !mine && (!prev || prev.from !== m.from);
      if (m.kind === "system") { html += '<div class="msg-row" style="align-self:center"><div class="bubble sys">' + esc(m.text) + "</div></div>"; return; }
      let body = "";
      if (m.kind === "voice") body = '<div class="voice-msg" data-voice="' + esc(m.id) + '"><span class="vplay">' + icon("play", 16) + '</span><span class="bars">' + Array.from({ length: 28 }, (_, k) => '<i style="height:' + (4 + Math.abs(Math.sin(k * 1.7 + i)) * 16) + 'px"></i>').join("") + "</span><span class=\"time\">" + esc((m.text.match(/\d+:\d\d/) || ["0:12"])[0]) + "</span></div>";
      else if (m.kind === "file") body = '<span class="file-chip">' + icon("file", 16) + " " + esc(m.file ? m.file.name : m.text) + '<span class="muted" style="font-size:11px">' + esc(m.file ? m.file.size : "") + "</span></span>";
      else if (m.kind === "call") body = icon("phone", 14) + " " + esc(m.text);
      else body = esc(m.text);
      const rx = Object.keys(m.reactions || {}).length ? '<div style="margin-top:4px;font-size:12px">' + Object.entries(m.reactions).map(([e, n]) => '<span class="chip" style="padding:1px 7px">' + e + " " + n + "</span>").join(" ") + "</div>" : "";
      html += '<div class="msg-row ' + (mine ? "mine" : "") + '" data-mid="' + esc(m.id) + '">' + (!mine && r.type === "group" ? '<span data-pp="' + esc(m.from) + '" style="cursor:pointer;align-self:flex-end">' + avatar(p, 30, false) + "</span>" : "") + '<div style="min-width:0">' + (showName ? '<div class="msg-group-name" data-pp="' + esc(m.from) + '" style="cursor:pointer">' + esc(p.name) + "</div>" : "") + '<div class="bubble">' + body + '<div class="meta">' + fmtTime(m.at) + (mine ? " ✓✓" : "") + "</div>" + rx + "</div></div></div>";
    });
    box.innerHTML = html; box.scrollTop = box.scrollHeight;
    $$("[data-pp]", box).forEach((e) => (e.onclick = () => profilePopup(personX(e.dataset.pp))));
    $$("[data-voice]", box).forEach((e) => { const m = r.messages.find((x) => x.id === e.dataset.voice); e.onclick = () => (m && m.playable ? Call.playVoice() : toast("Demo: this voice message carries no audio.")); });
    $$(".bubble", box).forEach((b) => { b.oncontextmenu = (e) => { e.preventDefault(); const mid = b.closest("[data-mid]").dataset.mid; const m = r.messages.find((x) => x.id === mid); popover(e.clientX, e.clientY, '<b>Message</b><div class="row">' + S.settings.reactions.map((x) => '<button class="chip" data-rx="' + x + '">' + x + "</button>").join("") + '</div><div class="row"><button class="chip" data-act="reply">Reply</button><button class="chip" data-act="fwd">Forward</button><button class="chip" data-act="del">Delete</button></div>'); $$("[data-rx]").forEach((c) => (c.onclick = () => { m.reactions[c.dataset.rx] = (m.reactions[c.dataset.rx] || 0) + 1; closePop(); paintMsgs(r); })); $$("[data-act]").forEach((c) => (c.onclick = () => { closePop(); if (c.dataset.act === "del") { r.messages = r.messages.filter((x) => x.id !== mid); paintMsgs(r); toast("Deleted for you (demo)"); } else toast("Demo: " + (c.dataset.act === "reply" ? "reply" : "forward") + " works like in the app — nothing leaves this page."); })); }; });
  }
  function send(r, m) {
    const msg = Object.assign({ id: uid(), from: "allison", at: NOW(), reactions: {} }, m); r.messages.push(msg); paintMsgs(r); renderNav();
    if (r.type === "dm" && r.personId === "demonstrator") { setTimeout(() => reply(r, "demonstrator", rnd(["Nice — that works exactly like the real app.", "Everything you type here stays on this page.", "Try the Music Library next; I'll wait."])), 1500); return; }
    const responders = r.type === "dm" ? [r.personId] : r.memberIds.filter((i) => i !== "allison");
    if (r.type === "group" && Math.random() < 0.35) return;
    const who = rnd(responders); const pool = (D.autoReplies[who] || []).concat(D.autoReplies._generic || ["Got it!"]);
    const text = rnd(pool); const delay = 1200 + Math.random() * 2500;
    S.typing[r.id] = who; if (curRoomId === r.id) $("#typing").textContent = nameOf(who) + " is typing…";
    setTimeout(() => { delete S.typing[r.id]; if (curRoomId === r.id) $("#typing").textContent = ""; reply(r, who, text); }, delay);
  }
  function reply(r, who, text) { r.messages.push({ id: uid(), from: who, kind: "text", text, at: NOW(), reactions: {} }); if (curRoomId === r.id) paintMsgs(r); else { S.unread[r.id] = (S.unread[r.id] || 0) + 1; if (S.settings.notif.messages) toast(nameOf(who) + ": " + text.slice(0, 60)); } renderNav(); if (page === "chat" && curRoomId !== r.id) renderChat(curRoomId); }
  function simCall(r, kind) {
    const who = r.type === "dm" ? personX(r.personId).name : roomTitle(r);
    const m = modal((kind === "video" ? "Video" : "Voice") + " call", '<div style="text-align:center"><div class="call-card" style="box-shadow:none;border:0;padding:8px"><div class="big">' + esc(initials(who)) + '</div><div class="nm">' + esc(who) + '</div><div class="st" id="simSt">calling…</div><div class="wave">' + "<i></i>".repeat(20) + '</div></div><p class="muted" style="font-size:13px">Calls in this demo are simulated: your music ducks for the duration and comes back when you hang up.</p></div>', [{ label: "Hang up", cls: "danger", onClick: () => { Player.duck(false); r.messages.push({ id: uid(), from: "allison", kind: "call", text: (kind === "video" ? "Video" : "Voice") + " call · 0:0" + (3 + Math.floor(Math.random() * 6)), at: NOW(), reactions: {} }); paintMsgs(r); } }], { sticky: true });
    Player.duck(true); setTimeout(() => { const s = $("#simSt", m); if (s) s.textContent = "connected · demo"; }, 1800);
  }
  const GS_INFO = "While the session is ACTIVE, the voice messages of the selected speakers are delivered LIVE to everyone in the group who keeps them selected — a live conversation in front of the group. Deactivate it (for example for the whole week) and activate it for your Friday 5 pm meeting, or let the schedule do it. A member hears it only while this group chat is open in their Chat page.";
  const GS_WARN = "This speaker was selected by the group admin. If you deselect them you may miss out on the group discussion. Deselect anyway?";
  function groupInfo(r) {
    const isAdmin = r.adminId === "allison"; const gs = r.instantSpeech;
    const body = () => '<div class="muted" style="font-size:13px">' + esc(r.topic || "") + "</div>" +
      '<div class="kx-block"><div class="kx-h">Instant speech session <span data-gsinfo></span></div><div class="kx-d" id="gsStatus">' + (gs.active ? "● ACTIVE — live speakers: " + (gs.speakers.map(nameOf).join(", ") || "none selected") : "○ inactive — speakers when active: " + (gs.speakers.map(nameOf).join(", ") || "none selected")) + (gs.schedule && gs.schedule.enabled ? " · scheduled Fri " + gs.schedule.from + "–" + gs.schedule.to : "") + "</div>" + (isAdmin ? '<div class="row" style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn sm ' + (gs.active ? "danger" : "primary") + '" id="gsToggle">' + (gs.active ? "Deactivate instant speech" : "Activate instant speech") + '</button><label class="chip"><input type="checkbox" id="gsSched" ' + (gs.schedule.enabled ? "checked" : "") + '> Fridays ' + esc(gs.schedule.from) + "–" + esc(gs.schedule.to) + "</label></div>" : '<div class="muted" style="font-size:12px">Only the group admin activates or deactivates the session.</div>') + "</div>" +
      '<div class="section-head" style="margin:14px 0 6px"><b>Group Speech Priority</b><span class="muted" style="font-size:12px">Each member\'s O# is assigned by the admin on the corporate page. Set an order # per member; when no order # is set, the O#s drive the hierarchy.</span></div>' +
      '<div style="display:grid;grid-template-columns:36px 1fr auto auto;gap:10px;font-size:11px;color:var(--ink-3);padding:0 6px"><span></span><span></span><span>' + (isAdmin ? "Instant Speech" : "Hear live") + '</span><span>Admin O#</span></div>' +
      r.memberIds.map((id) => { const p = personX(id); const self = id === "allison"; const on = isAdmin ? gs.speakers.includes(id) : (gs.speakers.includes(id) && !r.listenExcept.has(id)); const dis = self || (!isAdmin && !gs.speakers.includes(id)); return '<div class="member-row">' + avatar(p, 32, true) + '<div><b>' + esc(p.name) + (self ? " (you)" : "") + (id === r.adminId ? ' <span class="chip" style="font-size:10px;padding:1px 7px">admin</span>' : "") + '</b><div class="muted" style="font-size:12px">' + esc(p.title || "") + '</div></div><input type="checkbox" data-gsm="' + esc(id) + '" ' + (on ? "checked" : "") + (dis ? " disabled" : "") + ' title="' + (isAdmin ? "Select as a live speaker for this group" : gs.speakers.includes(id) ? "Untick to stop hearing this speaker live" : "Not selected by the admin") + '"><span class="o">' + esc(p.oNumber || "") + "</span></div>"; }).join("") +
      '<div class="kx-block" style="margin-top:16px"><div class="kx-h">Play an audio file for the group</div><div class="kx-d">Pick an audio file from your Files page; it is posted to the group and delivered live to members with instant listening.</div><div style="display:flex;gap:8px;flex-wrap:wrap"><select class="input" id="gsFile" style="max-width:280px">' + D.files.filter((f) => f.kind === "audio").map((f) => '<option value="' + esc(f.id) + '">' + esc(f.name) + "</option>").join("") + '</select><button class="btn sm" id="gsPreview">Preview</button><button class="btn sm primary" id="gsPlay">Play for the group</button></div></div>' +
      '<div style="margin-top:14px;display:flex;gap:8px"><button class="btn sm ghost danger" id="leaveGrp">Leave group</button></div>';
    const m = modal(roomTitle(r), body(), [{ label: "Close" }]);
    const wire = () => {
      const ii = $("[data-gsinfo]", m); if (ii) ii.appendChild(infoI(GS_INFO));
      $$("[data-gsm]", m).forEach((cb) => (cb.onchange = () => { const id = cb.dataset.gsm; if (isAdmin) { gs.speakers = cb.checked ? gs.speakers.concat([id]) : gs.speakers.filter((x) => x !== id); r.messages.push({ id: uid(), from: "system", kind: "system", text: "🎙 " + nameOf(id) + (cb.checked ? " was selected as a live speaker" : " is no longer a live speaker") + " by " + S.me.name + ".", at: NOW() }); } else { if (!cb.checked && !confirm(GS_WARN)) { cb.checked = true; return; } if (cb.checked) r.listenExcept.delete(id); else r.listenExcept.add(id); } refresh(); }));
      const t = $("#gsToggle", m); if (t) t.onclick = () => { gs.active = !gs.active; if (!gs.active) gs.schedule.enabled = false; r.messages.push({ id: uid(), from: "system", kind: "system", text: gs.active ? "🎙 Instant speech session STARTED by " + S.me.name + "." : "🔇 Instant speech session ENDED by " + S.me.name + ".", at: NOW() }); refresh(); };
      const sc = $("#gsSched", m); if (sc) sc.onchange = () => { gs.schedule.enabled = sc.checked; refresh(); };
      $("#gsPreview", m).onclick = () => toast("Demo: audio files in this demo are placeholders — nothing plays."); $("#gsPlay", m).onclick = () => { const f = D.files.find((x) => x.id === $("#gsFile", m).value); r.messages.push({ id: uid(), from: "allison", kind: "voice", text: (f ? f.name : "audio") + " · played for the group", at: NOW(), reactions: {} }); toast("Posted to the group (demo: placeholder audio, nothing plays)."); refresh(); };
      $("#leaveGrp", m).onclick = () => { if (!confirm("Leave " + roomTitle(r) + "?")) return; S.rooms = S.rooms.filter((x) => x.id !== r.id); closeModal(); location.hash = "#/chat"; toast("You left " + roomTitle(r) + " (demo)."); };
    };
    const refresh = () => { $(".modal-body", m).innerHTML = body(); wire(); if (curRoomId === r.id) { paintMsgs(r); const tt = $("#threadTitle"); if (tt) tt.innerHTML = esc(roomTitle(r)) + (gs.active ? ' <span class="chip" style="background:var(--rust);color:#fff;border-color:transparent;font-size:10px">● LIVE instant speech</span>' : ""); } };
    wire();
  }
  const SIGNS = [["voiceover", "Voice-over priority", "priority"], ["live", "Live Instant Communication", "livevoice"], ["chat", "Chat", "chat"], ["phone", "Phone", "phone"], ["video", "Video", "video"]];
  const VO_DESC = "Voice-over priority (the voice-over sign next to each contact): a priority contact's voice automatically ducks your music and can speak over it any time you're playing music — not only during shared listening. Tap the sign to give or remove it. The live-voice sign grants that contact Live Instant Communication — they reach you live even past the corporate shield. Signs marked with a small person show the contact's own stance toward you (display only — hover them to read it).";
  function signState(id) { return S.signs[id] || (S.signs[id] = { voiceover: false, live: false, chat: true, phone: true, video: true }); }
  function profilePopup(p) {
    if (!p || p.id === "allison") { location.hash = "#/profile"; return; }
    const sg = signState(p.id); const local = (() => { try { return new Date().toLocaleTimeString(undefined, { timeZone: p.timezone, hour: "2-digit", minute: "2-digit" }); } catch (e) { return ""; } })();
    const m = modal(p.name, '<div style="display:flex;gap:14px;align-items:center">' + avatar(p, 64, true) + '<div><div class="display" style="font-size:20px">' + esc(p.name) + '</div><div class="muted">' + esc(p.title || "") + (p.department ? " · " + esc(p.department) : "") + '</div><div class="mono muted" style="font-size:12px">' + esc(p.oNumber || "") + (p.city ? " · " + esc(p.city) : "") + (local ? " · local time " + local : "") + "</div></div></div>" + (p.bio ? '<p class="muted" style="margin:12px 0 0">' + esc(p.bio) + "</p>" : "") + '<div class="kx-block"><div class="kx-h">Signs for ' + esc(p.name.split(" ")[0]) + ' <span data-vo></span></div><div style="display:flex;gap:4px;flex-wrap:wrap">' + SIGNS.map(([k, label, ic]) => '<button class="icon-btn ' + (sg[k] ? "on" : "") + '" data-sign="' + k + '" title="' + esc(label) + '">' + icon(ic, 18) + "</button>").join("") + '</div><div class="muted" style="font-size:12px">Right-click a sign for its hours.</div></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="btn sm primary" id="ppMsg">Message</button><button class="btn sm" id="ppCall">Call</button><button class="btn sm" id="ppAdd">' + (S.contacts.has(p.id) ? "Remove contact" : "Add contact") + '</button><button class="btn sm ghost danger" id="ppBlock">' + (S.blocked.has(p.id) ? "Unblock" : "Block") + "</button></div>", []);
    $("[data-vo]", m).appendChild(infoI(VO_DESC));
    $$("[data-sign]", m).forEach((b) => { b.onclick = () => { sg[b.dataset.sign] = !sg[b.dataset.sign]; b.classList.toggle("on", sg[b.dataset.sign]); toast(b.title + (sg[b.dataset.sign] ? " given" : " removed") + " for " + p.name); }; b.oncontextmenu = (e) => { e.preventDefault(); hoursPopover(e.clientX, e.clientY, p, b.title); }; });
    $("#ppMsg", m).onclick = () => { closeModal(); openDm(p.id); }; $("#ppCall", m).onclick = () => { closeModal(); openDm(p.id); setTimeout(() => simCall(room("dm:" + p.id), "voice"), 200); };
    $("#ppAdd", m).onclick = () => { if (S.contacts.has(p.id)) S.contacts.delete(p.id); else S.contacts.add(p.id); closeModal(); toast(S.contacts.has(p.id) ? p.name + " added to your contacts" : p.name + " removed from your contacts"); if (page === "contacts") renderContacts(""); };
    $("#ppBlock", m).onclick = () => { if (S.blocked.has(p.id)) S.blocked.delete(p.id); else S.blocked.add(p.id); closeModal(); toast(S.blocked.has(p.id) ? p.name + " blocked — no calls, no live voice, no messages (demo)" : p.name + " unblocked"); };
  }
  function hoursPopover(x, y, p, sign) {
    const hr = S.hours[p.id + sign] || (S.hours[p.id + sign] = { from: "09:00", to: "17:00", days: [1, 2, 3, 4, 5] });
    const pp = popover(x, y, '<b>' + esc(p.name) + " — " + esc(sign) + ' hours</b><div class="muted">This sign only works from this contact inside this window.</div><div class="row">From <input class="input" style="width:80px" data-h="from" value="' + hr.from + '"> to <input class="input" style="width:80px" data-h="to" value="' + hr.to + '"></div><div class="row">' + ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((d, i) => '<button class="chip ' + (hr.days.includes(i) ? "on" : "") + '" data-d="' + i + '">' + d + "</button>").join("") + '</div><div class="row" style="justify-content:space-between;align-items:center"><span><button class="chip on" data-set>Set</button> <button class="chip" data-clear>Clear</button></span><span data-info></span></div>');
    $("[data-info]", pp).appendChild(infoI(VO_DESC));
    $$("[data-d]", pp).forEach((b) => (b.onclick = () => { const d = Number(b.dataset.d); hr.days = hr.days.includes(d) ? hr.days.filter((x) => x !== d) : hr.days.concat([d]); b.classList.toggle("on"); }));
    $("[data-set]", pp).onclick = () => { hr.from = $('[data-h="from"]', pp).value; hr.to = $('[data-h="to"]', pp).value; closePop(); toast("Hours set for " + sign + " (demo)"); }; $("[data-clear]", pp).onclick = () => { delete S.hours[p.id + sign]; closePop(); toast("Hours cleared"); };
  }
  function openDm(pid) { let r = room("dm:" + pid); if (!r) { r = { id: "dm:" + pid, type: "dm", personId: pid, name: nameOf(pid), messages: [], disappearing: "off" }; S.rooms.push(r); } location.hash = "#/chat/" + encodeURIComponent(r.id); }

  // ---------------- CONTACTS ----------------
  function renderContacts(q) {
    const main = $("#main"); const all = S.people.slice().sort((a, b) => a.name.localeCompare(b.name));
    main.innerHTML = '<div class="page-pad page-wide"><div class="eyebrow">Directory</div><h1 class="display" style="font-size:34px;margin:0 0 12px">Contacts</h1><input class="input" id="cq" placeholder="Search people to add or message" value="' + esc(q) + '" style="max-width:520px;margin-bottom:18px"><div id="cres"></div><div class="section-head"><h3 style="margin:0">My contacts</h3><span class="muted" style="font-size:12px" id="ccount"></span></div><div id="clist"></div><div class="section-head"><h3 style="margin:0">Rooms</h3></div><div class="muted" style="font-size:13px">' + esc(D.company.name) + " Lobby — an open room for the company. Say hi 👋</div></div>";
    const row = (p, inList) => { const sg = signState(p.id); return '<div class="contact-row" data-cid="' + esc(p.id) + '">' + avatar(p, 48, true) + '<div><div class="nm">' + esc(p.name) + (S.blocked.has(p.id) ? ' <span class="chip" style="font-size:10px">blocked</span>' : "") + '</div><div class="sub">' + esc(p.title || "") + " · " + esc(p.department || "") + " · " + esc(p.oNumber || "") + " · " + esc(p.status) + '</div></div><div class="acts">' + (inList ? SIGNS.map(([k, label, ic]) => '<button class="icon-btn ' + (sg[k] ? "on" : "") + '" data-sign="' + k + '" title="' + esc(label) + '">' + icon(ic, 18) + "</button>").join("") + '<button class="icon-btn" data-add title="Add to group">' + icon("plus", 18) + '</button><button class="icon-btn" data-rm title="Remove contact">' + icon("trash", 18) + "</button>" : '<button class="btn sm primary" data-addc>Add</button><button class="btn sm" data-msg>Message</button>') + "</div></div>"; };
    const paint = () => { const qq = ($("#cq").value || "").trim().toLowerCase(); const mine = all.filter((p) => S.contacts.has(p.id)); const found = qq ? all.filter((p) => (p.name + " " + p.title + " " + p.department).toLowerCase().includes(qq)) : []; $("#cres").innerHTML = qq ? '<div class="section-head" style="margin-top:0"><h3 style="margin:0">Search results</h3></div>' + (found.map((p) => row(p, S.contacts.has(p.id))).join("") || '<div class="muted">No one matches.</div>') : ""; $("#clist").innerHTML = mine.filter((p) => !qq || found.includes(p)).map((p) => row(p, true)).join("") || '<div class="muted" style="padding:16px 0">No contacts yet. Search above and tap <b>Add</b>.</div>'; $("#ccount").textContent = mine.length + " total · " + mine.filter((p) => signState(p.id).voiceover).length + " priority contacts stay on top"; wire(); };
    const wire = () => { $$(".contact-row").forEach((r) => { const p = personX(r.dataset.cid); $(".nm", r).onclick = () => profilePopup(p); $(".avatar", r).onclick = () => profilePopup(p); $$("[data-sign]", r).forEach((b) => { b.onclick = () => { const sg = signState(p.id); sg[b.dataset.sign] = !sg[b.dataset.sign]; b.classList.toggle("on", sg[b.dataset.sign]); toast(b.title + (sg[b.dataset.sign] ? " given" : " removed") + " for " + p.name); paint(); }; b.oncontextmenu = (e) => { e.preventDefault(); hoursPopover(e.clientX, e.clientY, p, b.title); }; }); const a = $("[data-add]", r); if (a) a.onclick = () => toast("Demo: pick a group in Chat to add " + p.name + "."); const rm = $("[data-rm]", r); if (rm) rm.onclick = () => { S.contacts.delete(p.id); toast(p.name + " removed from your contacts"); paint(); }; const ac = $("[data-addc]", r); if (ac) ac.onclick = () => { S.contacts.add(p.id); toast(p.name + " added"); paint(); }; const mg = $("[data-msg]", r); if (mg) mg.onclick = () => openDm(p.id); r.ondblclick = () => openDm(p.id); }); };
    $("#cq").oninput = paint; paint();
  }

  // ---------------- MUSIC ----------------
  function cardAlbum(a) { return '<button class="card" data-al="' + esc(a.id) + '"><img class="art" src="' + esc(a.cover) + '" alt=""><div class="t">' + esc(a.title) + '</div><div class="a">' + esc(artist(a.artistId).name) + " · " + esc(a.year) + "</div></button>"; }
  function cardPl(p) { return '<button class="card" data-pl="' + esc(p.id) + '"><img class="art" src="' + esc(p.cover) + '" alt=""><div class="t">' + esc(p.name) + '</div><div class="a">' + p.trackIds.length + " tracks</div></button>"; }
  function trackRow(t, i) { const a = album(t.albumId); return '<button class="track-row" data-tr="' + esc(t.id) + '"><span class="idx">' + (i + 1) + '</span><span><div class="tt">' + esc(t.title) + '</div><div class="ta">' + esc(artist(t.artistId).name) + (a ? " · " + esc(a.title) : "") + '</div></span><span class="icon-btn shelf" data-shelf="' + esc(t.id) + '" title="Save to your shelf">' + icon(S.shelf.has(t.id) ? "check" : "shelf", 16) + '</span><span class="dur">' + esc(t.duration) + "</span></button>"; }
  function renderMusic() {
    const main = $("#main"); const M = D.music; let html = '<div class="page-pad page-wide">';
    const head = (eyebrow, title, sub) => '<div class="eyebrow">' + esc(eyebrow) + '</div><h1 class="display" style="font-size:32px;margin:0 0 6px">' + esc(title) + '</h1>' + (sub ? '<p class="muted" style="margin:0 0 18px">' + esc(sub) + "</p>" : "");
    const sub = musicSub;
    if (sub.kind === "home") {
      html += '<div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-end;flex-wrap:wrap"><div>' + head("Music", "The Music Library", "Curated by the Kitaak Music team for " + D.company.name + " · Corporate Music Club") + '</div><div style="display:flex;gap:8px;margin-bottom:18px"><input class="input" id="mq" placeholder="Search songs, albums, artists" style="width:260px"><a class="btn sm" href="#/music/shelf">My shelf (' + S.shelf.size + ")</a></div></div>";
      html += '<div class="hero" style="margin-bottom:8px"><img src="' + esc(M.albums[0].cover) + '" style="width:220px;height:220px;border-radius:var(--r-lg);object-fit:cover"><div><div class="eyebrow">Kitaak recommendations for ' + esc(S.me.name.split(" ")[0]) + '</div><h2 class="display" style="font-size:26px;margin:6px 0">Picked for the genres you listen to most</h2><p class="muted">' + esc(S.me.favoriteGenres.map((g) => (genre(g) || {}).name).filter(Boolean).join(" · ")) + ' — based on your past music selections.</p><div style="display:flex;gap:8px;flex-wrap:wrap">' + M.albums.filter((a) => S.me.favoriteGenres.includes(a.genreId)).slice(0, 3).map((a) => '<button class="btn sm" data-al="' + esc(a.id) + '">' + icon("play", 14) + " " + esc(a.title) + "</button>").join("") + "</div></div></div>";
      M.sections.forEach((s) => { html += '<div class="section-head"><h3 style="margin:0">' + esc(s.title) + "</h3></div>"; if (s.kind === "albums") html += '<div class="hrow">' + s.itemIds.map(album).filter(Boolean).map(cardAlbum).join("") + "</div>"; else if (s.kind === "playlists") html += '<div class="hrow">' + s.itemIds.map(playlist).filter(Boolean).map(cardPl).join("") + "</div>"; else if (s.kind === "genres") html += '<div class="genre-grid">' + s.itemIds.map(genre).filter(Boolean).map((g) => '<button class="genre-tile" data-ge="' + esc(g.id) + '"><img src="' + esc(g.cover) + '" alt=""><b>' + esc(g.name) + "</b></button>").join("") + "</div>"; else if (s.kind === "tracks") html += '<div class="track-list">' + s.itemIds.map((id) => tracksById[id]).filter(Boolean).map(trackRow).join("") + "</div>"; });
      html += '<div class="section-head"><h3 style="margin:0">All genres</h3></div><div class="genre-grid">' + M.genres.map((g) => '<button class="genre-tile" data-ge="' + esc(g.id) + '"><img src="' + esc(g.cover) + '" alt=""><b>' + esc(g.name) + "</b></button>").join("") + "</div>";
    } else if (sub.kind === "album") { const a = album(sub.id); if (!a) { location.hash = "#/music"; return; } html += '<a class="back-link" href="#/music">' + icon("back", 14) + ' Music Library</a><div class="album-hero"><img src="' + esc(a.cover) + '" alt=""><div>' + head("Album · " + (genre(a.genreId) || {}).name, a.title, artist(a.artistId).name + " · " + a.year + " · " + a.tracks.length + " tracks") + '<div style="display:flex;gap:8px"><button class="btn primary" data-play-all="' + esc(a.id) + '">' + icon("play", 16) + ' Play</button><button class="btn" data-shelf-al="' + esc(a.id) + '">' + icon("shelf", 16) + ' Save to shelf</button><button class="btn" data-dl>' + icon("download", 16) + " Download</button></div></div></div><div class=\"track-list\">" + a.tracks.map((t, i) => trackRow(tracksById[t.id], i)).join("") + "</div>";
    } else if (sub.kind === "genre") { const g = genre(sub.id); if (!g) { location.hash = "#/music"; return; } const als = D.music.albums.filter((a) => a.genreId === g.id); html += '<a class="back-link" href="#/music">' + icon("back", 14) + ' Music Library</a>' + head("Genre", g.name, g.description) + '<div class="hrow" style="flex-wrap:wrap">' + als.map(cardAlbum).join("") + "</div>" + (als.length ? '<div class="section-head"><h3 style="margin:0">Tracks</h3></div><div class="track-list">' + als.flatMap((a) => a.tracks.map((t) => tracksById[t.id])).slice(0, 20).map(trackRow).join("") + "</div>" : "");
    } else if (sub.kind === "playlist") { const p = playlist(sub.id); if (!p) { location.hash = "#/music"; return; } html += '<a class="back-link" href="#/music">' + icon("back", 14) + ' Music Library</a><div class="album-hero"><img src="' + esc(p.cover) + '" alt=""><div>' + head("Playlist", p.name, p.description) + '<button class="btn primary" data-play-pl="' + esc(p.id) + '">' + icon("play", 16) + " Play</button></div></div><div class=\"track-list\">" + p.trackIds.map((id) => tracksById[id]).filter(Boolean).map(trackRow).join("") + "</div>";
    } else if (sub.kind === "shelf") { const ts = Array.from(S.shelf).map((id) => tracksById[id]).filter(Boolean); html += '<a class="back-link" href="#/music">' + icon("back", 14) + ' Music Library</a>' + head("Shelf", "My shelf", ts.length ? ts.length + " saved songs — ready to download in the full app." : "Save songs from any album or playlist; they show up here.") + '<div class="track-list">' + ts.map(trackRow).join("") + "</div>";
    } else if (sub.kind === "search") { const q = sub.q.toLowerCase(); const ts = Object.values(tracksById).filter((t) => (t.title + " " + artist(t.artistId).name).toLowerCase().includes(q)); const als = D.music.albums.filter((a) => (a.title + " " + artist(a.artistId).name).toLowerCase().includes(q)); html += '<a class="back-link" href="#/music">' + icon("back", 14) + ' Music Library</a>' + head("Search", '"' + sub.q + '"', als.length + " albums · " + ts.length + " songs") + (als.length ? '<div class="hrow">' + als.map(cardAlbum).join("") + "</div>" : "") + '<div class="track-list">' + ts.slice(0, 40).map(trackRow).join("") + "</div>"; }
    html += "</div>"; main.innerHTML = html;
    $$("[data-al]").forEach((b) => (b.onclick = () => (location.hash = "#/music/album/" + encodeURIComponent(b.dataset.al))));
    $$("[data-pl]").forEach((b) => (b.onclick = () => (location.hash = "#/music/playlist/" + encodeURIComponent(b.dataset.pl))));
    $$("[data-ge]").forEach((b) => (b.onclick = () => (location.hash = "#/music/genre/" + encodeURIComponent(b.dataset.ge))));
    $$("[data-tr]").forEach((b) => (b.onclick = (e) => { if (e.target.closest("[data-shelf]")) return; const t = tracksById[b.dataset.tr]; noMusicPopup(t.title + " — " + artist(t.artistId).name); }));
    $$("[data-shelf]").forEach((b) => (b.onclick = (e) => { e.stopPropagation(); const id = b.dataset.shelf; if (S.shelf.has(id)) S.shelf.delete(id); else S.shelf.add(id); b.innerHTML = icon(S.shelf.has(id) ? "check" : "shelf", 16); toast(S.shelf.has(id) ? "Saved to your shelf (demo)" : "Removed from your shelf"); }));
    $$("[data-play-all]").forEach((b) => (b.onclick = () => noMusicPopup(album(b.dataset.playAll).title)));
    $$("[data-play-pl]").forEach((b) => (b.onclick = () => noMusicPopup(playlist(b.dataset.playPl).name)));
    $$("[data-shelf-al]").forEach((b) => (b.onclick = () => { album(b.dataset.shelfAl).tracks.forEach((t) => S.shelf.add(t.id)); toast("Album saved to your shelf (demo)"); renderMusic(); }));
    $$("[data-dl]").forEach((b) => (b.onclick = () => toast("Demo: downloads need the full application and a plan with downloads.")));
    const mq = $("#mq"); if (mq) mq.onkeydown = (e) => { if (e.key === "Enter" && mq.value.trim()) location.hash = "#/music/search?q=" + encodeURIComponent(mq.value.trim()); };
  }

  // ---------------- SEARCH (Dig) ----------------
  function renderSearch(q) {
    const main = $("#main"); main.innerHTML = '<div class="page-pad page-wide"><div class="eyebrow">Dig</div><h1 class="display" style="font-size:32px;margin:0 0 12px">Search everything</h1><input class="input" id="sq" placeholder="People, messages, songs, albums…" value="' + esc(q) + '" style="max-width:560px" autofocus><div id="sres" style="margin-top:18px"></div></div>';
    const paint = () => { const qq = $("#sq").value.trim().toLowerCase(); const out = $("#sres"); if (!qq) { out.innerHTML = '<div class="muted">Type to search across ' + S.people.length + " people, " + S.rooms.reduce((n, r) => n + r.messages.length, 0) + " messages and " + Object.keys(tracksById).length + " songs.</div>"; return; } const ppl = S.people.filter((p) => (p.name + " " + p.title + " " + p.department).toLowerCase().includes(qq)).slice(0, 8); const msgs = []; S.rooms.forEach((r) => r.messages.forEach((m) => { if (m.text && m.text.toLowerCase().includes(qq)) msgs.push({ r, m }); })); const ts = Object.values(tracksById).filter((t) => (t.title + " " + artist(t.artistId).name).toLowerCase().includes(qq)).slice(0, 8); out.innerHTML = (ppl.length ? '<div class="section-head" style="margin-top:0"><h3 style="margin:0">People</h3></div>' + ppl.map((p) => '<div class="contact-row" data-p="' + esc(p.id) + '" style="cursor:pointer">' + avatar(p, 40, true) + '<div><div class="nm">' + esc(p.name) + '</div><div class="sub">' + esc(p.title) + " · " + esc(p.department) + "</div></div><div></div></div>").join("") : "") + (msgs.length ? '<div class="section-head"><h3 style="margin:0">Messages (' + msgs.length + ')</h3></div>' + msgs.slice(0, 12).map(({ r, m }) => '<div class="contact-row" data-r="' + esc(r.id) + '" style="cursor:pointer;grid-template-columns:1fr auto"><div><div class="nm" style="font-size:13px">' + esc(roomTitle(r)) + ' · <span class="muted">' + esc(nameOf(m.from)) + '</span></div><div class="sub">' + esc(m.text.slice(0, 120)) + '</div></div><span class="conv-time">' + fmtConv(m.at) + "</span></div>").join("") : "") + (ts.length ? '<div class="section-head"><h3 style="margin:0">Songs</h3></div><div class="track-list">' + ts.map(trackRow).join("") + "</div>" : "") + (!ppl.length && !msgs.length && !ts.length ? '<div class="muted">Nothing found.</div>' : ""); $$("[data-p]", out).forEach((e) => (e.onclick = () => profilePopup(personX(e.dataset.p)))); $$("[data-r]", out).forEach((e) => (e.onclick = () => (location.hash = "#/chat/" + encodeURIComponent(e.dataset.r)))); $$("[data-tr]", out).forEach((b) => (b.onclick = () => { const t = tracksById[b.dataset.tr]; noMusicPopup(t.title); })); };
    $("#sq").oninput = paint; paint(); $("#sq").focus();
  }

  // ---------------- FILES ----------------
  const FICON = { doc: "📄", image: "🖼", sheet: "📊", audio: "🎵", pdf: "📕", slides: "📽" };
  function renderFiles() {
    const main = $("#main"); const files = D.files.slice().sort((a, b) => a.daysAgo - b.daysAgo);
    main.innerHTML = '<div class="page-pad page-wide"><div style="display:flex;justify-content:space-between;align-items:flex-end;flex-wrap:wrap;gap:12px"><div><div class="eyebrow">Media</div><h1 class="display" style="font-size:32px;margin:0 0 6px">Files</h1><p class="muted" style="margin:0 0 18px">Everything shared with you in chats and groups.</p></div><button class="btn primary" id="upBtn" style="margin-bottom:18px">' + icon("upload", 16) + ' Upload</button></div><div class="files-grid">' + files.map((f) => '<button class="file-card" data-f="' + esc(f.id) + '"><span class="fi">' + (FICON[f.kind] || "📎") + '</span><span style="min-width:0"><div class="fn">' + esc(f.name) + '</div><div class="fs">' + esc(f.size) + " · " + esc(nameOf(f.fromId)) + " · " + (f.roomId.startsWith("dm:") ? "direct" : esc((room(f.roomId) || {}).name || f.roomId)) + " · " + f.daysAgo + "d ago</div></span></button>").join("") + "</div></div>";
    $("#upBtn").onclick = () => toast("Demo: uploads are not saved — the Files page keeps its sample files.");
    $$("[data-f]").forEach((b) => (b.onclick = () => { const f = D.files.find((x) => x.id === b.dataset.f); modal(f.name, '<p class="muted">' + esc(f.kind) + " · " + esc(f.size) + " · shared by " + esc(nameOf(f.fromId)) + " · " + f.daysAgo + ' days ago</p><p class="muted" style="font-size:13px">' + esc(f.note || "") + '</p><p class="note" style="font-size:13px">Demo files are placeholders: nothing opens, plays or downloads here.</p>', [{ label: "Delete", cls: "danger", onClick: () => { D.files.splice(D.files.indexOf(f), 1); renderFiles(); toast("Moved to trash (demo)"); } }, { label: "Close" }]); }));
  }

  // ---------------- COMPANY (corporate page) ----------------
  function renderCompany() {
    const c = D.company; const admins = S.people.filter((p) => p.role === "admin"); const main = $("#main");
    main.innerHTML = '<div class="page-pad page-wide"><div class="hero"><span class="avatar" style="width:120px;height:120px;font-size:40px;border-radius:var(--r-lg)">' + esc(initials(c.name)) + '</span><div><div class="eyebrow">Corporate page · Corporate Music Club</div><h1 class="display" style="font-size:30px;margin:6px 0">' + esc(c.name) + '</h1><p class="muted" style="margin:0 0 8px">' + esc(c.tagline) + " · " + esc(c.industry) + " · " + esc(c.city) + ", " + esc(c.country) + '</p><p class="muted" style="font-size:13.5px">' + esc(c.description) + '</p><div style="display:flex;gap:8px;flex-wrap:wrap"><span class="chip">' + (S.people.length + 1) + ' members</span><span class="chip">' + D.groups.length + ' groups</span><span class="chip">' + admins.length + ' admins</span><span class="chip">workplace music: Kitaak Music Library</span></div></div></div>' +
      '<div class="section-head"><h3 style="margin:0">Announcements</h3></div>' + D.announcements.map((a) => '<div class="panel" style="margin-bottom:10px"><b>' + esc(a.title) + '</b> <span class="muted" style="font-size:12px">· ' + esc(nameOf(a.fromId)) + " · " + a.daysAgo + 'd ago</span><p class="muted" style="margin:6px 0 0;font-size:14px">' + esc(a.body) + "</p></div>").join("") +
      '<div class="section-head"><h3 style="margin:0">Admins</h3></div>' + admins.map((p) => '<div class="contact-row" data-p="' + esc(p.id) + '" style="cursor:pointer">' + avatar(p, 44, true) + '<div><div class="nm">' + esc(p.name) + '</div><div class="sub">' + esc(p.title) + " · " + esc(p.oNumber) + '</div></div><span class="chip">admin</span></div>').join("") +
      '<div class="section-head"><h3 style="margin:0">Departments</h3></div><div class="cards" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:10px">' + c.departments.map((d) => '<div class="panel" style="padding:14px"><b>' + esc(d) + '</b><div class="muted" style="font-size:12.5px">' + S.people.filter((p) => p.department === d).length + " people</div></div>").join("") + "</div>" +
      '<div class="section-head"><h3 style="margin:0">Members</h3><span class="muted" style="font-size:12px">O# is assigned by the admin; it drives the speaking order in groups</span></div><div>' + S.people.slice().sort((a, b) => Number(a.oNumber.slice(1)) - Number(b.oNumber.slice(1))).map((p) => '<div class="member-row" data-p="' + esc(p.id) + '" style="cursor:pointer">' + avatar(p, 32, true) + '<div><b>' + esc(p.name) + '</b><div class="muted" style="font-size:12px">' + esc(p.title) + " · " + esc(p.department) + '</div></div><span class="chip" style="font-size:11px">' + esc(p.status) + '</span><span class="o">' + esc(p.oNumber) + "</span></div>").join("") + "</div></div>";
    $$("[data-p]").forEach((e) => (e.onclick = () => profilePopup(personX(e.dataset.p))));
  }

  // ---------------- SETTINGS ----------------
  const TZS = ["auto", "America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "Europe/London", "Europe/Berlin", "Asia/Dubai", "Asia/Tokyo", "Australia/Sydney"];
  function renderSettings() {
    const st = S.settings; const main = $("#main");
    const row = (title, desc, ctl) => '<div class="setting-row"><div class="sr-main"><div class="sr-title">' + title + '</div><div class="sr-desc">' + desc + "</div></div>" + ctl + "</div>";
    main.innerHTML = '<div class="page-pad page-wide settings-compact"><div class="eyebrow">Settings</div><h1 class="display" style="font-size:32px;margin:0 0 16px">Make Kitaak yours</h1>' +
      '<div class="panel"><h3>Appearance</h3>' + row("Theme", "Paper is the daytime default; Wax and Noir are easier on the eyes at night.", '<div class="seg" id="themeSeg">' + ["paper", "wax", "noir"].map((t) => '<button class="' + (S.theme === t ? "on" : "") + '" data-t="' + t + '">' + t + "</button>").join("") + "</div>") + "</div>" +
      '<div class="panel" data-kx-autoadd="1"><h3>Contacts</h3>' + row("Automatically add anyone I chat, call, or video-call to my contacts", "When on, the other person is added to your contacts the first time you message or call them.", sw(st.autoAdd, 'data-s="autoAdd"')) + "</div>" +
      '<div class="panel"><h3>Time</h3>' + row("Time zone", "Automatic (Application Adjusted Time), Device Time, or a fixed IANA zone.", '<select class="input" id="tzSel" style="max-width:260px">' + ["Automatic (Application Adjusted Time)", "Device Time", "Local Time (IANA / GPS on mobile)"].map((l, i) => '<option value="' + ["auto", "device", "local"][i] + '"' + (st.tz === ["auto", "device", "local"][i] ? " selected" : "") + ">" + l + "</option>").join("") + TZS.slice(1).map((z) => '<option value="' + z + '"' + (st.tz === z ? " selected" : "") + ">" + z + "</option>").join("") + "</select>") + "</div>" +
      '<div class="panel"><h3>Notifications</h3><div class="panel-sub">Turn a category off to stop it notifying you (banner, sound, and badge for that type).</div>' + [["messages", "Messages", "New messages in chats and groups."], ["mentions", "Mentions", "When someone @mentions you."], ["calls", "Calls", "Voice and video calls."], ["music", "Music", "New releases and Kitaak Music news."]].map(([k, t, d]) => row(t, d, sw(st.notif[k], 'data-n="' + k + '"'))).join("") + row("Sounds", "Play a sound with banners.", sw(st.sounds, 'data-s="sounds"')) + "</div>" +
      '<div class="panel"><h3>Away &amp; Status</h3>' + row("Status line", "Shown next to your name in your profile popup.", '<input class="input" id="statusIn" placeholder="What are you up to?" value="' + esc(S.me.statusLine) + '" style="max-width:280px">') + '<div style="display:flex;gap:6px;flex-wrap:wrap;padding:6px 0">' + D.statuses.map((s) => '<button class="chip" data-st="' + esc(s) + '">' + esc(s) + "</button>").join("") + "</div>" + row("Away after", "Mark me away after this many minutes without activity.", '<select class="input" id="awaySel" style="max-width:160px">' + ["5", "10", "30", "never"].map((v) => '<option' + (st.awayAfter === v ? " selected" : "") + ">" + v + "</option>").join("") + "</select>") + "</div>" +
      '<div class="panel"><h3>Reactions</h3>' + row("Quick reactions", "The four reactions offered on every message (right-click a message).", '<div style="display:flex;gap:6px" id="rxRow">' + ["👍", "❤️", "🔥", "🎧", "😂", "🎉", "👀", "✅", "🙏"].map((e) => '<button class="chip ' + (st.reactions.includes(e) ? "on" : "") + '" data-rx="' + e + '">' + e + "</button>").join("") + "</div>") + "</div>" +
      '<div class="panel"><h3>Disappearing Messages</h3>' + row("Default timer for new chats", "New conversations start with this auto-delete timer. You can override it per chat.", '<select class="input" id="disSel" style="max-width:180px">' + ["off", "24 hours", "7 days", "30 days"].map((v) => '<option' + (st.disappearing === v ? " selected" : "") + ">" + v + "</option>").join("") + "</select>") + '<p class="faint mono" style="font-size:11px">Corporate: disappearing chats are still reported to your admin for compliance.</p></div>' +
      '<div class="panel"><h3>Voice Options</h3>' + row("ISA — Instant speech to all members", "Only you set this for yourself — your voice reaches everyone in a group live.", sw(st.isa, 'data-s="isa"')) + row("ISM — Instant Speech of Members", "Live delivery of voice messages of all members to you. Select this together with ISA for a live group meeting.", sw(st.ism, 'data-s="ism"')) + row("Duck level during conversations", "How low the music goes while someone talks to you (" + st.duck + "% of your volume). Hear it when the Digital Demonstrator calls.", '<input type="range" min="5" max="60" value="' + st.duck + '" id="duckRange" style="width:160px;accent-color:var(--rust)">') + "</div>" +
      '<div class="panel"><h3>Security</h3>' + row("Change password", "Use at least 10 characters.", '<div style="display:flex;gap:6px;flex-wrap:wrap"><input class="input" type="password" placeholder="New password" id="pw1" style="width:150px"><input class="input" type="password" placeholder="Repeat" id="pw2" style="width:120px"><button class="btn sm" id="pwBtn">Update</button></div>') + row("Active sessions", "This browser · signed in now.", '<button class="btn sm" id="signOutAll">Sign out other devices</button>') + "</div>" +
      '<div class="panel"><h3>Billing</h3>' + row("Your plan", "Corporate Music Club via " + esc(D.company.name) + " — billed to your company.", '<a class="btn sm" href="#/membership">Membership page</a>') + "</div>" +
      '<div class="panel"><h3>Privacy &amp; Blocklist</h3>' + row("Blocked people", S.blocked.size ? Array.from(S.blocked).map(nameOf).join(", ") : "Nobody is blocked. Block someone from their profile popup.", S.blocked.size ? '<button class="btn sm" id="unblockAll">Unblock all</button>' : "") + row("Read receipts", "Let others see when you have read their messages.", sw(true, 'data-s="rr"')) + "</div>" +
      '<div class="panel"><h3 style="color:var(--danger)">Sensitive Functions</h3>' + row("Delete my profile", "Removes your profile details and leaves every group. In this demo the page simply resets.", '<button class="btn sm danger" id="delProfile">Delete profile</button>') + row("Close my account", "Closes the account for good. In this demo the page simply resets.", '<button class="btn sm danger" id="closeAcc">Close account</button>') + "</div></div>";
    $$("#themeSeg button").forEach((b) => (b.onclick = () => { S.theme = b.dataset.t; document.documentElement.dataset.theme = S.theme; renderSettings(); }));
    $$("[data-s]").forEach((el) => wireSwitch(el, (on) => { st[el.dataset.s] = on; toast((el.closest(".setting-row") ? $(".sr-title", el.closest(".setting-row")).textContent : "Setting") + ": " + (on ? "on" : "off")); }));
    $$("[data-n]").forEach((el) => wireSwitch(el, (on) => { st.notif[el.dataset.n] = on; }));
    $("#tzSel").onchange = (e) => { st.tz = e.target.value; toast("Time mode: " + e.target.selectedOptions[0].textContent + " ✓"); };
    $("#statusIn").onchange = (e) => { S.me.statusLine = e.target.value; toast("Status saved (demo)"); }; $$("[data-st]").forEach((b) => (b.onclick = () => { S.me.statusLine = b.dataset.st; $("#statusIn").value = b.dataset.st; toast("Status: " + b.dataset.st); }));
    $("#awaySel").onchange = (e) => (st.awayAfter = e.target.value);
    $$("[data-rx]").forEach((b) => (b.onclick = () => { const e = b.dataset.rx; if (st.reactions.includes(e)) st.reactions = st.reactions.filter((x) => x !== e); else if (st.reactions.length < 4) st.reactions.push(e); else { toast("Pick at most four quick reactions"); return; } renderSettings(); }));
    $("#disSel").onchange = (e) => { st.disappearing = e.target.value; toast("Default timer: " + st.disappearing); };
    $("#duckRange").oninput = (e) => { st.duck = Number(e.target.value); $(".sr-desc", $("#duckRange").closest(".setting-row")).textContent = "How low the music goes while someone talks to you (" + st.duck + "% of your volume)."; if (Player.ducked) Player.duck(true); };
    $("#pwBtn").onclick = () => { const a = $("#pw1").value, b = $("#pw2").value; if (a.length < 10) return toast("Use at least 10 characters."); if (a !== b) return toast("The two passwords differ."); $("#pw1").value = $("#pw2").value = ""; toast("Password updated (demo — nothing is stored)"); };
    $("#signOutAll").onclick = () => toast("Other devices signed out (demo)"); const ub = $("#unblockAll"); if (ub) ub.onclick = () => { S.blocked.clear(); renderSettings(); toast("Blocklist cleared"); };
    $("#delProfile").onclick = () => sensitive("delete your profile"); $("#closeAcc").onclick = () => sensitive("close your account");
  }
  function sensitive(what) { modal("Sensitive function", '<p>You are about to <b>' + esc(what) + "</b>.</p><p class=\"muted\">In the real application this removes your data and cannot be undone. In this demo the page resets to its starting point.</p>", [{ label: "Cancel" }, { label: "Yes, " + what, cls: "danger", onClick: () => { document.body.innerHTML = '<div class="welcome"><div class="box"><div class="eyebrow">Kitaak demo</div><h1>Done — the demo profile is gone.</h1><p>That is exactly what happens in the application. Because this is a demo, the account comes back the moment the page reloads.</p><button class="btn primary" onclick="location.reload()">Reload the demo</button></div></div>'; } }]); }

  // ---------------- PROFILE ----------------
  function renderProfile() {
    const me = S.me; const main = $("#main"); const F = [["title", "Title"], ["department", "Department"], ["phone", "Phone"], ["email", "Email"], ["city", "City"], ["bio", "Bio"]];
    main.innerHTML = '<div class="page-pad page-wide settings-compact"><div class="eyebrow">Profile</div><div style="display:flex;gap:16px;align-items:center;margin:6px 0 18px">' + avatar(me, 72, true) + '<div><h1 class="display" style="font-size:30px;margin:0">' + esc(me.name) + '</h1><div class="muted mono" style="font-size:12px">' + esc(me.oNumber) + " · " + esc(D.company.name) + " · Corporate Music Club" + (me.statusLine ? " · " + esc(me.statusLine) : "") + '</div></div></div><div class="panel"><h3>Your details</h3><div class="panel-sub">Private unless you check <b>Public\'s</b> — then it shows on your profile popup.</div>' + '<div class="field"><label class="sr-title">Name</label><input class="input" data-f="name" value="' + esc(me.name) + '"></div>' + F.map(([k, l]) => '<div class="field" style="display:grid;grid-template-columns:1fr auto;gap:10px;align-items:end"><div><label class="sr-title">' + l + "</label>" + (k === "bio" ? '<textarea class="input" data-f="bio" rows="2">' + esc(me.bio || "") + "</textarea>" : '<input class="input" data-f="' + k + '" value="' + esc(me[k] || "") + '">') + '</div><label class="chip"><input type="checkbox" data-pub="' + k + '" ' + (me.pub[k] ? "checked" : "") + "> Public</label></div>").join("") + '<div style="display:flex;gap:8px;margin-top:10px"><button class="btn primary" id="saveProf">Save profile</button><button class="btn" id="avatarBtn">Change photo</button></div></div>' +
      '<div class="panel"><h3 style="color:var(--danger)">Sensitive Functions</h3><div class="setting-row"><div class="sr-main"><div class="sr-title">Delete my profile</div><div class="sr-desc">Removes your profile details and leaves every group.</div></div><button class="btn sm danger" id="delProfile2">Delete profile</button></div></div></div>';
    $("#saveProf").onclick = () => { $$("[data-f]").forEach((i) => (me[i.dataset.f] = i.value.trim())); $$("[data-pub]").forEach((c) => (me.pub[c.dataset.pub] = c.checked)); me.initials = initials(me.name); $("#bannerWho").textContent = "Signed in as " + me.name; renderNav(); renderProfile(); toast("Profile saved (demo — not stored anywhere)"); };
    $("#avatarBtn").onclick = () => toast("Demo: photos are not uploaded; your initials stay."); $("#delProfile2").onclick = () => sensitive("delete your profile");
  }

  // ---------------- MEMBERSHIP ----------------
  function renderMembership() {
    const main = $("#main"); const cur = "corporate_music_club";
    main.innerHTML = '<div class="page-pad page-wide"><div style="display:flex;justify-content:space-between;align-items:flex-end;flex-wrap:wrap;gap:12px"><div><div class="eyebrow">Membership</div><h1 class="display" style="font-size:34px;margin:0">Choose your plan</h1></div><div style="display:flex;gap:8px"><button class="btn" id="giftBtn">' + icon("membercard", 16) + ' Gift A Membership</button><button class="btn" id="redeemBtn">Redeem a code</button></div></div><p class="muted" style="margin:8px 0 18px">You\'re on <b>Corporate Music Club</b> via ' + esc(D.company.name) + '. Family &amp; corporate plans ask for a token or send you to the payment page.</p><div class="plan-grid">' + PLANS.map((p) => '<div class="plan ' + (p.tier === cur ? "current" : "") + '"><div class="eyebrow">' + esc(p.kind) + (p.popular ? " · popular" : "") + '</div><h3>' + esc(p.name) + '</h3><div class="price">' + (p.price ? "$" + p.price : "Free") + '<span class="muted" style="font-size:12px;font-weight:400"> ' + (p.price ? "/ month" + (p.perSeat ? " / seat" : "") : "") + '</span></div><ul>' + (p.features || []).map((f) => "<li>" + esc(f) + "</li>").join("") + '</ul><button class="btn ' + (p.tier === cur ? "" : "primary") + '" data-plan="' + esc(p.tier) + '" ' + (p.tier === cur ? "disabled" : "") + ">" + (p.tier === cur ? "Current plan" : p.price === 0 ? "Switch to Digger" : "Get " + esc(p.name)) + "</button></div>").join("") + "</div></div>";
    $$("[data-plan]").forEach((b) => (b.onclick = (e) => { const p = PLANS.find((x) => x.tier === b.dataset.plan); if (p.kind === "corporate" || p.kind === "family") { const pp = popover(e.clientX, e.clientY, "<b>Get " + esc(p.name) + '</b><div class="muted">Do you already have a plan token — a Sign Up Code from your company or family administrator, or a Kitaak gift code? Enter it to join that plan without paying now. Otherwise continue to the payment page.</div><div class="row"><input class="input" placeholder="Plan token / Sign Up Code / gift code" style="text-transform:uppercase"></div><div class="row"><button class="chip on" data-tok>Use my token</button><button class="chip" data-pay>Go to payment page</button></div>'); $("[data-tok]", pp).onclick = () => { closePop(); toast("Demo: tokens are not checked here — in the app this joins the plan instantly."); }; $("[data-pay]", pp).onclick = () => { closePop(); toast("Demo: the payment page is not part of the demo."); }; } else toast("Demo: no payments are processed here."); }));
    $("#giftBtn").onclick = () => modal("Gift A Membership", '<div class="field"><label class="sr-title">Plan</label><select class="input">' + PLANS.filter((p) => p.price > 0).map((p) => "<option>" + esc(p.name) + "</option>").join("") + '</select></div><div class="field"><label class="sr-title">Length</label><select class="input"><option>1 month</option><option>3 months</option><option>6 months</option><option>12 months</option></select></div><div class="field"><label class="sr-title">Recipient (name or email)</label><input class="input" placeholder="Who is it for?"></div><div class="field"><label class="sr-title">Gift note</label><textarea class="input" rows="2">You\'ve been gifted Kitaak 🎧 — enjoy the music.</textarea></div>', [{ label: "Cancel" }, { label: "Create gift code", cls: "primary", onClick: () => toast("Demo: gift codes are created in the full application only.") }]);
    $("#redeemBtn").onclick = () => modal("Redeem a token or gift code", '<p class="muted">Enter a Kitaak gift code, or a Sign Up Code from your company or family administrator.</p><input class="input" placeholder="Gift code / Sign Up Code" style="text-transform:uppercase">', [{ label: "Close" }, { label: "Redeem", cls: "primary", onClick: () => toast("Demo: codes are not checked here.") }]);
  }

  // ---------------- boot ----------------
  function welcome() {
    const w = h('<div class="welcome"><div class="box"><div class="eyebrow">Kitaak · web demo</div><h1>Welcome, you are signed in as ' + esc(S.me.name) + '.</h1><p>This is a live corporate account at <b>' + esc(D.company.name) + '</b> with ' + S.people.length + ' colleagues. Everything works — chat, groups, contacts, the music library, settings, your profile — and <b>nothing you do is saved</b>.</p><ul><li>Send a message; your colleagues answer.</li><li>Background music starts when you enter; the library shows the catalog but its songs carry no audio in this demo.</li><li>A colleague will call you a few seconds after you enter — answer to hear the music duck and come back.</li></ul><button class="btn primary" id="enterBtn" style="width:100%;justify-content:center">Enter the demo</button></div></div>');
    document.body.appendChild(w);
    $("#enterBtn", w).onclick = () => { w.remove(); Player.start(); S.started = NOW(); setTimeout(() => Call.incoming(), 7400); toast("Background music on — a colleague will call you in a few seconds."); };
  }
  $("#resetBtn").onclick = () => location.reload();
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") { closeModal(); closePop(); } });
  document.addEventListener("click", (e) => { const a = e.target.closest("a[href^='#/']"); if (a && a.classList.contains("nav-item")) { /* let the hash change */ } });
  renderPlayer(); route(); welcome();
})();
